import {
  VRA,
  MAT,
  ELE,
  TEO,
  ELP,
  FIS,
  QIM,
  BIO,
  EDU,
  PSI,
  LET,
  INT,
  DEF,
  FON,
  MEF,
  IEU,
  CLG,
  SOL,
  IHI,
  ICP,
  ANT,
  GEO,
  EAE,
  OPR,
  MIN,
  X,
  FIL,
  OFG
} from "./colors";

export const ramos2016 = [
  {
    id: 1,
    code: "MAT1000",
    course: "Precálculo",
    semester: "I",
    year: 1,
    cc: MAT,
    cr: 10,
    req: [],
  },
  {
    id: 2,
    code: "SOL100",
    course: "Paradigmas Sociológicos",
    semester: "I",
    year: 1,
    cc: SOL,
    cr: 10,
    req: [],
  },
  {
    id: 3,
    code: "EAE105A",
    course: "Introducción a la Economía",
    semester: "I",
    year: 1,
    cc: EAE,
    cr: 10,
    req: [],
  },
  {
    id: 4,
    code: "PSI1101",
    course: "Procesos Psicológicos Básicos",
    semester: "I",
    year: 1,
    cc: PSI,
    cr: 10,
    req: [],
  },
  {
    id: 5,
    course: "AFG Salud y Bienestar",
    semester: "I",
    year: 1,
    cc: OFG,
    cr: 10,
    req: [],
  },
  {
    id: 6,
    code: "CLG0901",
    course: "Taller de Iniciación",
    semester: "I",
    year: 1,
    cc: CLG,
    req: [],
  },
  {
    id: 7,
    code: "VRA100C",
    course: "Español",
    semester: "I",
    year: 1,
    cc: VRA,
    req: [],
  },
  {
    id: 8,
    code: "VRA2000",
    course: "English Test",
    semester: "I",
    year: 1,
    cc: VRA,
    req: [],
  },

  {
    id: 9,
    code: "VRA4000",
    course: "Integridad Académica",
    semester: "I",
    year: 1,
    cc: VRA,
    req: [],
  },
  {
    id: 10,
    code: "IHI",
    course: "Mínimo Historia",
    semester: "II",
    year: 1,
    cc: IHI,
    cr: 10,
    req: [],
  },
  {
    id: 11,
    code: "ICP",
    course: "Mínimo Ciencia Política",
    semester: "II",
    year: 1,
    cc: ICP,
    cr: 10,
    req: [],
  },
  {
    id: 12,
    code: "GEO103",
    course: "Geografía Humana General",
    semester: "II",
    year: 1,
    cc: GEO,
    cr: 10,
    req: [],
  },
  {
    id: 13,
    code: "SOL312",
    course: "Antropología de la Convivencia Social",
    semester: "II",
    year: 1,
    cc: SOL,
    cr: 10,
    req: [],
  },
  {
    id: 14,
    course: "AFG Liberada",
    semester: "II",
    year: 1,
    cc: OFG,
    cr: 10,
    req: [],
  },
  {
    id: 15,
    course: "Optativo",
    semester: "III",
    year: 2,
    cc: OPR,
    cr: 10,
    req: [],
  },
  {
    id: 16,
    course: "Optativo",
    semester: "III",
    year: 2,
    cc: OPR,
    cr: 10,
    req: [],
  },
  {
    id: 17,
    course: "Exploratorio",
    semester: "III",
    year: 2,
    cc: OPR,
    cr: 10,
    req: [],
  },
  {
    id: 18,
    course: "Exploratorio",
    semester: "III",
    year: 2,
    cc: OPR,
    cr: 10,
    req: [],
  },
  {
    id: 19,
    course: "AFG Matematico",
    semester: "III",
    year: 2,
    cc: OFG,
    cr: 10,
    req: [],
  },
  {
    id: 20,
	  code: "SOL126S",
    course: "Metodología de la Investigación Social",
    semester: "IV",
    year: 2,
    cc: SOL,
    cr: 10,
    req: [],
  },
  {
    id: 21,
    course: "Exploratorio",
    semester: "IV",
    year: 2,
    cc: OPR,
    cr: 10,
    req: [],
  },
  {
    id: 22,
    course: "Exploratorio",
    semester: "IV",
    year: 2,
    cc: OPR,
    cr: 10,
    req: [],
  },
  {
    id: 23,
    course: "Minor",
    semester: "IV",
    year: 2,
    cc: MIN,
    cr: 10,
    req: [],
  },
  {
    id: 24,
	code: "FIL2001",
    course: "Filosofía: ¿Para Qué?",
    semester: "IV",
    year: 2,
    cc: OFG,
    cr: 10,
    req: [],
  },
  {
    id: 25,
	  code: "IEU2020",
    course: "Lógicas Territoriales",
    semester: "V",
    year: 3,
    cc: IEU,
    cr: 10,
    req: [],
  },
  {
    id: 26,
	  code: "IEU2028",
    course: "La Ciudad: Historia y Procesos",
    semester: "V",
    year: 3,
    cc: IEU,
    cr: 10,
    req: [],
  },
  {
    id: 27,
	  code: "IEU2033",
    course: "Infraestructuras Urbanas",
    semester: "V",
    year: 3,
    cc: IEU,
    cr: 10,
    req: [],
  },
  {
    id: 28,
    course: "Minor",
    semester: "V",
    year: 3,
    cc: MIN,
    cr: 10,
    req: [],
  },
  {
    id: 29,
    course: "AFG Sustentabilidad",
    semester: "V",
    year: 3,
    cc: OFG,
    cr: 10,
    req: [],
  },
  {
    id: 30,
    code: "IEU2026",
    course: "Planificación Urbana: Teoría y Método",
    semester: "VI",
    year: 3,
    cc: IEU,
    cr: 10,
    req: [],
  },
  {
	id: 31,
	code: "IEU2031",  
	course: "Institucionalidad Territorial",
    semester: "VI",
    year: 3,
    cc: IEU,
    cr: 10,
    req: [],
  },
  {
    id: 32,
	code: "IEU2035",
    course: "IEU2035",
    semester: "VI",
    year: 3,
    cc: IEU,
    cr: 10,
    req: [],
  },
  {
    id: 33,
    course: "Minor",
    semester: "VI",
    year: 3,
    cc: MIN,
    cr: 10,
    req: [],
  },
  {
    id: 34,
    course: "AFG Artes",
    semester: "VI",
    year: 3,
    cc: OFG,
    cr: 10,
    req: [],
  },
  {
    id: 35,
    code: "IEU2029",
    course: "Vivienda y Forma Urbana",
    semester: "VII",
    year: 4,
    cc: IEU,
    cr: 10,
    req: [],
  },
  {
    id: 36,
    code: "IEU2030",
    course: "Análisis y Modelación de Datos Territoriales",
    semester: "VII",
    year: 4,
    cc: IEU,
    cr: 10,
    req: [],
  },
  {
    id: 37,
    code: "IEU2033",
    course: "Taller de Planificación Urbana I",
    semester: "VII",
    year: 4,
    cc: IEU,
    cr: 10,
    req: [],
  },
  {
    id: 38,
    course: "Minor",
    semester: "VII",
    year: 4,
    cc: MIN,
    cr: 10,
    req: [],
  },
  {
    id: 39,
    course: "AFG Tecnología",
    semester: "VII",
    year: 4,
    cc: OFG,
    cr: 10,
    req: [],
  },
  {
    id: 40,
    code: "IEU2034",
    course: "Comunidad y Construcción Social del Hábitat",
    semester: "VIII",
    year: 4,
    cc: IEU,
    cr: 10,
    req: [],
  },
  {
    id: 41,
    code: "IEU2036",
    course: "Taller de Planificación Urbana II",
    semester: "VIII",
    year: 4,
    cc: IEU,
    cr: 10,
    req: [],
  },
  {
    id: 42,
    code: "IEU2037",
    course: "Laboratorio de Evaluación Ambiental Urbana",
    semester: "VIII",
    year: 4,
    cc: IEU,
    cr: 10,
    req: [],
  },
  {
    id: 43,
    course: "Minor",
    semester: "VIII",
    year: 4,
    cc: MIN,
    cr: 10,
    req: [],
  },
  {
    id: 44,
    course: "AFG Teológico",
    semester: "VIII",
    year: 4,
    cc: OFG,
    cr: 10,
    req: [],
  },
]