import {
  VRA,
  TALLER,
  TEORICO,
  HERRAMIENTAS,
  CAMINO,
  HABILITACION,
} from "./colors";

export const ramosDirecta = [
  {
    id: 1,
    code: "IEU2101",
    course: "Taller de Introducción a la Planificación Urbana",
    semester: "I",
    year: 1,
    cc: TALLER,
    cr: 15,
    req: [],
  },
  {
    id: 2,
    code: "IEU2102",
    course: "Ciudad, Urbanización y Urbanismo",
    semester: "I",
    year: 1,
    cc: TEORICO,
    cr: 10,
    req: [],
  },
  {
    id: 3,
    code: "EAE105A",
    course: "Introducción a la Economía",
    semester: "I",
    year: 1,
    cc: TEORICO,
    cr: 10,
    req: [],
  },
  {
    id: 4,
    code: "MAT1000",
    course: "Precálculo",
    semester: "I",
    year: 1,
    cc: HERRAMIENTAS,
    cr: 10,
    req: [],
  },
  {
    id: 5,
    code: "VRA100C",
    course: "Español",
    semester: "I",
    year: 1,
    cc: VRA,
    req: [],
  },
  {
    id: 6,
    code: "VRA2000",
    course: "English Test",
    semester: "I",
    year: 1,
    cc: VRA,
    req: [],
  },
  {
    id: 7,
    code: "VRA4000",
    course: "Capacitación Integridad académica en la UC",
    semester: "I",
    year: 1,
    cc: VRA,
    req: [],
  },
  {
    id: 8,
    code: "IEU2103",
    course: "Taller de Planificación Multiescalar I",
    semester: "II",
    year: 1,
    cc: TALLER,
    cr: 15,
    req: [],
  },
  {
    id: 9,
    code: "IEU2104",
    course: "Teoría de la Planificación Urbana y Territorial",
    semester: "II",
    year: 1,
    cc: TEORICO,
    cr: 10,
    req: [],
  },
  {
    id: 10,
    code: "EYP230P",
    course: "Estadística",
    semester: "II",
    year: 1,
    cc: HERRAMIENTAS,
    cr: 10,
    req: [],
  },
  {
    id: 11,
    course: "Formación General",
    semester: "II",
    year: 1,
    cc: CAMINO,
    cr: 10,
    req: [],
  },
  {
    id: 12,
    course: "Formación General",
    semester: "II",
    year: 1,
    cc: CAMINO,
    cr: 10,
    req: [],
  },
  {
    id: 13,
    code: "IEU2105",
    course: "Taller de Planificación Multiescalar II",
    semester: "III",
    year: 2,
    cc: TALLER,
    cr: 15,
    req: [],
  },
  {
    id: 14,
    code: "GEO104",
    course: "Geografía Física General",
    semester: "III",
    year: 2,
    cc: TEORICO,
    cr: 10,
    req: [],
  },
  {
    id: 15,
    code: "IEU2106",
    course: "Economía Urbana y Regional",
    semester: "III",
    year: 2,
    cc: TEORICO,
    cr: 10,
    req: [],
  },
  {
    id: 16,
    code: "GEO3214",
    course: "Sistemas de Información Geográfica",
    semester: "III",
    year: 2,
    cc: HERRAMIENTAS,
    cr: 10,
    req: [],
  },
  {
    id: 17,
    code: "TTF",
    course: "Formación Teológica",
    semester: "III",
    year: 2,
    cc: CAMINO,
    cr: 10,
    req: [],
  },
  {
    id: 18,
    code: "IEU2107",
    course: "Taller de Diseño y Forma Urbana",
    semester: "IV",
    year: 2,
    cc: TALLER,
    cr: 15,
    req: [],
  },
  {
    id: 19,
    code: "IEU2109",
    course: "Institucionalidad y Legislación Urbana y Territorial",
    semester: "IV",
    year: 2,
    cc: TEORICO,
    cr: 10,
    req: [],
  },
  {
    id: 20,
    code: "IEU2108",
    course: "Técnicas de Representación Espacial",
    semester: "IV",
    year: 2,
    cc: HERRAMIENTAS,
    cr: 10,
    req: [],
  },
  {
    id: 21,
    code: "FIL2001",
    course: "Filosofía: ¿Para qué?",
    semester: "IV",
    year: 2,
    cc: CAMINO,
    cr: 10,
    req: [],
  },
  {
    id: 22,
    code: "IEU2110",
    course: "Taller de Planificación Urbana Regulatoria",
    semester: "V",
    year: 3,
    cc: TALLER,
    cr: 15,
    req: [],
  },
  {
    id: 23,
    code: "IEU2112",
    course: "Gobernanza y Ciudadanía",
    semester: "V",
    year: 3,
    cc: TEORICO,
    cr: 10,
    req: [],
  },
  {
    id: 24,
    code: "IEU2111",
    course: "Laboratorio de Evaluación Ambiental Urbana",
    semester: "V",
    year: 3,
    cc: HERRAMIENTAS,
    cr: 10,
    req: [],
  },
  {
    id: 25,
    course: "Formación General",
    semester: "V",
    year: 3,
    cc: CAMINO,
    cr: 10,
    req: [],
  },
  {
    id: 26,
    course: "Formación General",
    semester: "V",
    year: 3,
    cc: CAMINO,
    cr: 10,
    req: [],
  },
  {
    id: 27,
    code: "IEU2113",
    course: "Taller de Planificación Ecológica y Resiliencia Urbana",
    semester: "VI",
    year: 3,
    cc: TALLER,
    cr: 15,
    req: [],
  },
  {
    id: 28,
    code: "IEU2115",
    course: "Vivienda y Hábitat",
    semester: "VI",
    year: 3,
    cc: TEORICO,
    cr: 10,
    req: [],
  },
  {
    id: 29,
    code: "IEU2114",
    course: "Análisis de Datos Urbanos",
    semester: "VI",
    year: 3,
    cc: TEORICO,
    cr: 10,
    req: [],
  },
  {
    id: 30,
    course: "Formación General",
    semester: "VI",
    year: 3,
    cc: CAMINO,
    cr: 10,
    req: [],
  },
  {
    id: 31,
    code: "IEU2116",
    course: "Taller de Planificación Urbana Estratégica",
    semester: "VII",
    year: 4,
    cc: TALLER,
    cr: 15,
    req: [],
  },
  {
    id: 32,
    code: "IEU2117",
    course: "Movilidad Urbana y Transporte",
    semester: "VII",
    year: 4,
    cc: TEORICO,
    cr: 10,
    req: [],
  },
  {
    id: 33,
    course: "Minor",
    semester: "VII",
    year: 4,
    cc: CAMINO,
    cr: 10,
    req: [],
  },
  {
    id: 34,
    course: "Minor",
    semester: "VII",
    year: 4,
    cc: CAMINO,
    cr: 10,
    req: [],
  },
  {
    id: 35,
    course: "Formación General",
    semester: "VII",
    year: 4,
    cc: CAMINO,
    cr: 10,
    req: [],
  },
  {
    id: 36,
    code: "IEU2118",
    course: "Taller de Integración Interdisciplinar",
    semester: "VIII",
    year: 4,
    cc: TALLER,
    cr: 15,
    req: [],
  },
  {
    id: 37,
    course: "Minor",
    semester: "VIII",
    year: 4,
    cc: CAMINO,
    cr: 10,
    req: [],
  },
  {
    id: 38,
    course: "Minor",
    semester: "VIII",
    year: 4,
    cc: CAMINO,
    cr: 10,
    req: [],
  },
  {
    id: 39,
    course: "Minor",
    semester: "VIII",
    year: 4,
    cc: CAMINO,
    cr: 10,
    req: [],
  },
  {
    id: 40,
    code: "IEU2119",
    course: "Seminario de Título en Planificación Urbana",
    semester: "IX",
    year: 5,
    cc: HABILITACION,
    cr: 20,
    req: [],
  },
  {
    id: 41,
    code: "IEU2121",
    course: "Proyectos Urbanos: Gestión y Evaluación",
    semester: "IX",
    year: 5,
    cc: TEORICO,
    cr: 5,
    req: [],
  },
  {
    id: 42,
    code: "IEU2120",
    course: "Simulación Digital Urbana",
    semester: "IX",
    year: 5,
    cc: HERRAMIENTAS,
    cr: 5,
    req: [],
  },
  {
    id: 43,
    code: "OPT",
    course: "Optativo",
    semester: "IX",
    year: 5,
    cc: CAMINO,
    cr: 10,
    req: [],
  },
  {
    id: 44,
    code: "OPT",
    course: "Optativo",
    semester: "IX",
    year: 5,
    cc: CAMINO,
    cr: 10,
    req: [],
  },
  {
    id: 45,
    code: "IEU2122",
    course: "Práctica Profesional",
    semester: "X",
    year: 5,
    cc: HABILITACION,
    cr: 25,
    req: [],
  },
  {
    id: 46,
    code: "IEU2124",
    course: "Ética Profesional para la Planificación Urbana",
    semester: "X",
    year: 5,
    cc: TEORICO,
    cr: 5,
    req: [],
  },
  {
    id: 47,
    code: "IEU2123",
    course: "Planificación de Infraestructuras, Redes y Equipamientos",
    semester: "X",
    year: 5,
    cc: TEORICO,
    cr: 5,
    req: [],
  },
  {
    id: 48,
    code: "OPT",
    course: "Optativo",
    semester: "X",
    year: 5,
    cc: CAMINO,
    cr: 10,
    req: [],
  },
  {
    id: 49,
    code: "OPT",
    course: "Optativo",
    semester: "X",
    year: 5,
    cc: CAMINO,
    cr: 10,
    req: [],
  },
];
