import {
  VRA,
  MAT,
  ELP,
  FIS,
  QIM,
  BIO,
  EDU,
  PSI,
  LET,
  INT,
  DEF,
  FON,
  MEF,
  IEU,
  CLG,
  SOL,
  IHI,
  ICP,
  ANT,
  GEO,
  EAE,
  OPR,
  MIN,
  X,
  OFG,
  IEU32,
  OPR32
} from "./colors";

export const ramos2023 = [
  {
    id: 1,
    code: "CLG0000",
    course: "Seminario College",
    semester: "I",
    year: 1,
    cc: CLG,
    cr: 10,
    req: [],
  },
  {
    id: 2,
    code: "SOL500",
    course: "¿Qué es la Sociología?",
    semester: "I",
    year: 1,
    cc: SOL,
    cr: 10,
    req: [],
  },
  {
    id: 3,
    code: "MAT1000",
    course: "Precálculo",
    semester: "I",
    year: 1,
    cc: MAT,
    cr: 10,
    req: [],
  },
  {
    id: 4,
    code: "PSI1101",
    course: "Procesos Psicológicos Básicos",
    semester: "I",
    year: 1,
    cc: PSI,
    cr: 10,
    req: [],
  },
  {
    id: 5,
    code: "IHI0205",
    course: "Historia Mundial Contemporánea",
    semester: "I",
    year: 1,
    cc: IHI,
    cr: 10,
    req: [],
  },
  {
    id: 6,
    code: "VRA100C",
    course: "Español",
    semester: "I",
    year: 1,
    cc: VRA,
    req: [],
  },

  {
    id: 7,
    code: "VRA2000",
    course: "English Test",
    semester: "I",
    year: 1,
    cc: VRA,
    req: [],
  },

  {
    id: 8,
    code: "VRA4000",
    course: "Integridad Académica",
    semester: "I",
    year: 1,
    cc: VRA,
    req: [],
  },
  {
    id: 9,
    code: "ICP0101",
    course: "Introducción a la Ciencia Política",
    semester: "II",
    year: 1,
    cc: ICP,
    cr: 10,
    req: [],
  },
  {
    id: 10,
    code: "ANT100",
    course: "Paradigmas Antropológicos",
    semester: "II",
    year: 1,
    cc: ANT,
    cr: 10,
    req: [],
  },
  {
    id: 11,
    code: "GEO103",
    course: "Geografía Humana General",
    semester: "II",
    year: 1,
    cc: GEO,
    cr: 10,
    req: [],
  },
  {
    id: 12,
    code: "EAE105",
    course: "Introducción a la Economía",
    semester: "II",
    year: 1,
    cc: EAE,
    cr: 10,
    req: [],
  },
  {
    id: 13,
    course: "Filosofía: ¿Para Qué?",
    semester: "II",
    year: 1,
    cc: OFG,
    cr: 10,
    req: [],
  },
  {
    id: 14,
    code: "CLG0020",
    course: "Exploraciones en Ciencias Sociales",
    semester: "III",
    year: 2,
    cc: CLG,
    cr: 10,
    req: [],
  },
  {
    id: 15,
    course: "Optativo",
    semester: "III",
    year: 2,
    cc: OPR,
    cr: 10,
    req: [],
  },
  {
    id: 16,
    course: "Optativo",
    semester: "III",
    year: 2,
    cc: OPR,
    cr: 10,
    req: [],
  },
  {
    id: 17,
    course: "Optativo",
    semester: "III",
    year: 2,
    cc: OPR,
    cr: 10,
    req: [],
  },
  {
    id: 18,
    course: "Formación General",
    semester: "III",
    year: 2,
    cc: OFG,
    cr: 10,
    req: [],
  },
  {
    id: 19,
    course: "Optativo",
    semester: "IV",
    year: 2,
    cc: OPR,
    cr: 10,
    req: [],
  },
  {
    id: 20,
    course: "Optativo",
    semester: "IV",
    year: 2,
    cc: OPR,
    cr: 10,
    req: [],
  },
  {
    id: 21,
    course: "Optativo",
    semester: "IV",
    year: 2,
    cc: OPR,
    cr: 10,
    req: [],
  },
  {
    id: 22,
    course: "Minor",
    semester: "IV",
    year: 2,
    cc: MIN,
    cr: 10,
    req: [],
  },
  {
    id: 23,
    course: "Formación General",
    semester: "IV",
    year: 2,
    cc: OFG,
    cr: 10,
    req: [],
  },
  {
    id: 24,
    code: "IEU2062",
    course: "La Ciudad: Historia y Procesos",
    semester: "V",
    year: 3,
    cc: IEU,
    cr: 10,
    req: [],
  },
  {
    id: 25,
	code: "IEU2063",
    course: "Planificación Urbana: Teoría y Método",
    semester: "V",
    year: 3,
    cc: IEU,
    cr: 10,
    req: [],
  },
  {
    id: 26,
    course: "Optativo",
    semester: "V",
    year: 3,
    cc: OPR,
    cr: 10,
    req: [],
  },
  {
    id: 27,
    course: "Minor",
    semester: "V",
    year: 3,
    cc: MIN,
    cr: 10,
    req: [],
  },
  {
    id: 28,
    course: "Formación General",
    semester: "V",
    year: 3,
    cc: OFG,
    cr: 10,
    req: [],
  },
  {
    id: 29,
    code: "IEU2060",
    course: "Institucionalidad y Legislación Urbana-Territorial",
    semester: "VI",
    year: 3,
    cc: IEU,
    cr: 10,
    req: [],
  },
  {
    id: 30,
    code: "IEU2061",
    course: "Gobernanza y Participación Ciudadana",
    semester: "VI",
    year: 3,
    cc: IEU,
    cr: 10,
    req: [],
  },
  {
    id: 31,
    code: "IEU2064",
    course: "Análisis y Modelación de Datos Territoriales",
    semester: "VI",
    year: 3,
    cc: IEU,
    cr: 10,
    req: [],
  },
  {
    id: 32,
    course: "Minor",
    semester: "VI",
    year: 3,
    cc: MIN,
    cr: 10,
    req: [],
  },
  {
    id: 33,
    course: "Formación General",
    semester: "VI",
    year: 3,
    cc: OFG,
    cr: 10,
    req: [],
  },
  {
    id: 34,
    code: "IEU2053",
    course: "Taller de Gestión y Estrategias Territoriales (A+S)",
    semester: "VII",
    year: 4,
    cc: IEU,
    cr: 15,
    req: [
      { id: 29, cc: IEU },
      { id: 30, cc: IEU },
	  { id: 31, cc: IEU },
    ],
  },
  {
    id: 35,
    code: "IEU2065",
    course: "Técnicas de Representación Espacial",
    semester: "VII",
    year: 4,
    cc: IEU,
    cr: 10,
    req: [
		{ id: 31, cc: IEU },
	],
  },
  {
    id: 36,
    course: "Optativo",
    semester: "VII",
    year: 4,
    cc: OPR,
    cr: 10,
    req: [],
  },
  {
    id: 37,
    course: "Minor",
    semester: "VII",
    year: 4,
    cc: MIN,
    cr: 10,
    req: [],
  },
  {
    id: 38,
    code: "",
    course: "Formación General",
    semester: "VII",
    year: 4,
    cc: OFG,
    cr: 10,
    req: [],
  },
  {
    id: 39,
    code: "IEU2054",
    course: "Taller de Instrumentos de Planificación Territorial y Urbana",
    semester: "VIII",
    year: 4,
    cc: IEU,
    cr: 15,
    req: [
      { id: 34, cc: IEU },
    ],
  },
  {
    id: 40,
    code: "IEU2066",
    course: "Laboratorio de Evaluación Ambiental Urbana",
    semester: "VIII",
    year: 4,
    cc: IEU,
    cr: 10,
    req: [{ id: 29, cc: IEU }],
  },
  
  {
    id: 41,
    course: "Minor",
    semester: "VIII",
    year: 4,
    cc: MIN,
    cr: 10,
    req: [],
  },
  {
    id: 42,
    course: "Formación Teológica",
    semester: "VIII",
    year: 4,
    cc: OFG,
    cr: 10,
    req: [],
  }, 
  {
    id: 43,
    code: "IEU3200",
    course: "Teoría y Ética de la Planificación",
    semester: "IX",
    year: 5,
    cc: IEU32,
    cr: 10,
    req: [
		{ id: 1, cc: CLG },
		{ id: 2, cc: SOL },
		{ id: 3, cc: MAT },
		{ id: 4, cc: PSI },
		{ id: 5, cc: IHI },
		{ id: 6, cc: VRA },
		{ id: 7, cc: VRA },
		{ id: 8, cc: VRA },
		{ id: 9, cc: ICP },
		{ id: 10, cc: ANT },
		{ id: 11, cc: GEO },
		{ id: 12, cc: EAE },
		{ id: 13, cc: OFG },
		{ id: 14, cc: CLG },
		{ id: 15, cc: OPR },
		{ id: 16, cc: OPR },
		{ id: 17, cc: OPR },
		{ id: 18, cc: OFG },
		{ id: 19, cc: OPR },
		{ id: 20, cc: OPR },
		{ id: 21, cc: OPR },
		{ id: 22, cc: MIN },
		{ id: 23, cc: OFG },
		{ id: 24, cc: IEU },
		{ id: 25, cc: IEU },
		{ id: 26, cc: OPR },
		{ id: 27, cc: MIN },
		{ id: 28, cc: OFG },
		{ id: 29, cc: IEU },
		{ id: 30, cc: IEU },
		{ id: 31, cc: IEU },
		{ id: 32, cc: MIN },
		{ id: 33, cc: OFG },
		{ id: 34, cc: IEU },
		{ id: 35, cc: IEU },
		{ id: 36, cc: OPR },
		{ id: 37, cc: MIN },
		{ id: 38, cc: OFG },
		{ id: 39, cc: IEU },
		{ id: 40, cc: IEU },
		{ id: 41, cc: MIN },
		{ id: 42, cc: OFG },
	]
  },
  {
    id: 44,
    code: "IEU3201",
    course: "Métodos de Análisis Urbano",
    semester: "IX",
    year: 5,
    cc: IEU32,
    cr: 10,
    req: [
		{ id: 1, cc: CLG },
		{ id: 2, cc: SOL },
		{ id: 3, cc: MAT },
		{ id: 4, cc: PSI },
		{ id: 5, cc: IHI },
		{ id: 6, cc: VRA },
		{ id: 7, cc: VRA },
		{ id: 8, cc: VRA },
		{ id: 9, cc: ICP },
		{ id: 10, cc: ANT },
		{ id: 11, cc: GEO },
		{ id: 12, cc: EAE },
		{ id: 13, cc: OFG },
		{ id: 14, cc: CLG },
		{ id: 15, cc: OPR },
		{ id: 16, cc: OPR },
		{ id: 17, cc: OPR },
		{ id: 18, cc: OFG },
		{ id: 19, cc: OPR },
		{ id: 20, cc: OPR },
		{ id: 21, cc: OPR },
		{ id: 22, cc: MIN },
		{ id: 23, cc: OFG },
		{ id: 24, cc: IEU },
		{ id: 25, cc: IEU },
		{ id: 26, cc: OPR },
		{ id: 27, cc: MIN },
		{ id: 28, cc: OFG },
		{ id: 29, cc: IEU },
		{ id: 30, cc: IEU },
		{ id: 31, cc: IEU },
		{ id: 32, cc: MIN },
		{ id: 33, cc: OFG },
		{ id: 34, cc: IEU },
		{ id: 35, cc: IEU },
		{ id: 36, cc: OPR },
		{ id: 37, cc: MIN },
		{ id: 38, cc: OFG },
		{ id: 39, cc: IEU },
		{ id: 40, cc: IEU },
		{ id: 41, cc: MIN },
		{ id: 42, cc: OFG },
	]
  },
  {
    id: 45,
    code: "IEU3202",
    course: "Economía y Desarrollo Urbano",
    semester: "IX",
    year: 5,
    cc: IEU32,
    cr: 10,
    req: [
		{ id: 1, cc: CLG },
		{ id: 2, cc: SOL },
		{ id: 3, cc: MAT },
		{ id: 4, cc: PSI },
		{ id: 5, cc: IHI },
		{ id: 6, cc: VRA },
		{ id: 7, cc: VRA },
		{ id: 8, cc: VRA },
		{ id: 9, cc: ICP },
		{ id: 10, cc: ANT },
		{ id: 11, cc: GEO },
		{ id: 12, cc: EAE },
		{ id: 13, cc: OFG },
		{ id: 14, cc: CLG },
		{ id: 15, cc: OPR },
		{ id: 16, cc: OPR },
		{ id: 17, cc: OPR },
		{ id: 18, cc: OFG },
		{ id: 19, cc: OPR },
		{ id: 20, cc: OPR },
		{ id: 21, cc: OPR },
		{ id: 22, cc: MIN },
		{ id: 23, cc: OFG },
		{ id: 24, cc: IEU },
		{ id: 25, cc: IEU },
		{ id: 26, cc: OPR },
		{ id: 27, cc: MIN },
		{ id: 28, cc: OFG },
		{ id: 29, cc: IEU },
		{ id: 30, cc: IEU },
		{ id: 31, cc: IEU },
		{ id: 32, cc: MIN },
		{ id: 33, cc: OFG },
		{ id: 34, cc: IEU },
		{ id: 35, cc: IEU },
		{ id: 36, cc: OPR },
		{ id: 37, cc: MIN },
		{ id: 38, cc: OFG },
		{ id: 39, cc: IEU },
		{ id: 40, cc: IEU },
		{ id: 41, cc: MIN },
		{ id: 42, cc: OFG },
	]
  },
  {
    id: 46,
    code: "IEU3212",
    course: "Taller de Planificación Urbana Estratégica",
    semester: "IX",
    year: 5,
    cc: IEU32,
    cr: 15,
    req: [
		{ id: 1, cc: CLG },
		{ id: 2, cc: SOL },
		{ id: 3, cc: MAT },
		{ id: 4, cc: PSI },
		{ id: 5, cc: IHI },
		{ id: 6, cc: VRA },
		{ id: 7, cc: VRA },
		{ id: 8, cc: VRA },
		{ id: 9, cc: ICP },
		{ id: 10, cc: ANT },
		{ id: 11, cc: GEO },
		{ id: 12, cc: EAE },
		{ id: 13, cc: OFG },
		{ id: 14, cc: CLG },
		{ id: 15, cc: OPR },
		{ id: 16, cc: OPR },
		{ id: 17, cc: OPR },
		{ id: 18, cc: OFG },
		{ id: 19, cc: OPR },
		{ id: 20, cc: OPR },
		{ id: 21, cc: OPR },
		{ id: 22, cc: MIN },
		{ id: 23, cc: OFG },
		{ id: 24, cc: IEU },
		{ id: 25, cc: IEU },
		{ id: 26, cc: OPR },
		{ id: 27, cc: MIN },
		{ id: 28, cc: OFG },
		{ id: 29, cc: IEU },
		{ id: 30, cc: IEU },
		{ id: 31, cc: IEU },
		{ id: 32, cc: MIN },
		{ id: 33, cc: OFG },
		{ id: 34, cc: IEU },
		{ id: 35, cc: IEU },
		{ id: 36, cc: OPR },
		{ id: 37, cc: MIN },
		{ id: 38, cc: OFG },
		{ id: 39, cc: IEU },
		{ id: 40, cc: IEU },
		{ id: 41, cc: MIN },
		{ id: 42, cc: OFG },
	]
  },
  {
    id: 47,
    code: "IEU3209",
    course: "Infraestructura, Redes y Equipamientos Urbanos",
    semester: "IX",
    year: 5,
    cc: IEU32,
    cr: 5,
    req: [
		{ id: 1, cc: CLG },
		{ id: 2, cc: SOL },
		{ id: 3, cc: MAT },
		{ id: 4, cc: PSI },
		{ id: 5, cc: IHI },
		{ id: 6, cc: VRA },
		{ id: 7, cc: VRA },
		{ id: 8, cc: VRA },
		{ id: 9, cc: ICP },
		{ id: 10, cc: ANT },
		{ id: 11, cc: GEO },
		{ id: 12, cc: EAE },
		{ id: 13, cc: OFG },
		{ id: 14, cc: CLG },
		{ id: 15, cc: OPR },
		{ id: 16, cc: OPR },
		{ id: 17, cc: OPR },
		{ id: 18, cc: OFG },
		{ id: 19, cc: OPR },
		{ id: 20, cc: OPR },
		{ id: 21, cc: OPR },
		{ id: 22, cc: MIN },
		{ id: 23, cc: OFG },
		{ id: 24, cc: IEU },
		{ id: 25, cc: IEU },
		{ id: 26, cc: OPR },
		{ id: 27, cc: MIN },
		{ id: 28, cc: OFG },
		{ id: 29, cc: IEU },
		{ id: 30, cc: IEU },
		{ id: 31, cc: IEU },
		{ id: 32, cc: MIN },
		{ id: 33, cc: OFG },
		{ id: 34, cc: IEU },
		{ id: 35, cc: IEU },
		{ id: 36, cc: OPR },
		{ id: 37, cc: MIN },
		{ id: 38, cc: OFG },
		{ id: 39, cc: IEU },
		{ id: 40, cc: IEU },
		{ id: 41, cc: MIN },
		{ id: 42, cc: OFG },
	]
  },
  {
    id: 48,
    code: "IEU3203",
    course: "Institucionalidad, Gobernanza y Gestión Urbana",
    semester: "X",
    year: 5,
    cc: IEU32,
    cr: 10,
    req: [
		{ id: 1, cc: CLG },
		{ id: 2, cc: SOL },
		{ id: 3, cc: MAT },
		{ id: 4, cc: PSI },
		{ id: 5, cc: IHI },
		{ id: 6, cc: VRA },
		{ id: 7, cc: VRA },
		{ id: 8, cc: VRA },
		{ id: 9, cc: ICP },
		{ id: 10, cc: ANT },
		{ id: 11, cc: GEO },
		{ id: 12, cc: EAE },
		{ id: 13, cc: OFG },
		{ id: 14, cc: CLG },
		{ id: 15, cc: OPR },
		{ id: 16, cc: OPR },
		{ id: 17, cc: OPR },
		{ id: 18, cc: OFG },
		{ id: 19, cc: OPR },
		{ id: 20, cc: OPR },
		{ id: 21, cc: OPR },
		{ id: 22, cc: MIN },
		{ id: 23, cc: OFG },
		{ id: 24, cc: IEU },
		{ id: 25, cc: IEU },
		{ id: 26, cc: OPR },
		{ id: 27, cc: MIN },
		{ id: 28, cc: OFG },
		{ id: 29, cc: IEU },
		{ id: 30, cc: IEU },
		{ id: 31, cc: IEU },
		{ id: 32, cc: MIN },
		{ id: 33, cc: OFG },
		{ id: 34, cc: IEU },
		{ id: 35, cc: IEU },
		{ id: 36, cc: OPR },
		{ id: 37, cc: MIN },
		{ id: 38, cc: OFG },
		{ id: 39, cc: IEU },
		{ id: 40, cc: IEU },
		{ id: 41, cc: MIN },
		{ id: 42, cc: OFG },
	]
  },
  {
    id: 49,
    code: "IEU3204",
    course: "Coproducción del Desarrollo Urbano",
    semester: "X",
    year: 5,
    cc: IEU32,
    cr: 10,
    req: [
		{ id: 1, cc: CLG },
		{ id: 2, cc: SOL },
		{ id: 3, cc: MAT },
		{ id: 4, cc: PSI },
		{ id: 5, cc: IHI },
		{ id: 6, cc: VRA },
		{ id: 7, cc: VRA },
		{ id: 8, cc: VRA },
		{ id: 9, cc: ICP },
		{ id: 10, cc: ANT },
		{ id: 11, cc: GEO },
		{ id: 12, cc: EAE },
		{ id: 13, cc: OFG },
		{ id: 14, cc: CLG },
		{ id: 15, cc: OPR },
		{ id: 16, cc: OPR },
		{ id: 17, cc: OPR },
		{ id: 18, cc: OFG },
		{ id: 19, cc: OPR },
		{ id: 20, cc: OPR },
		{ id: 21, cc: OPR },
		{ id: 22, cc: MIN },
		{ id: 23, cc: OFG },
		{ id: 24, cc: IEU },
		{ id: 25, cc: IEU },
		{ id: 26, cc: OPR },
		{ id: 27, cc: MIN },
		{ id: 28, cc: OFG },
		{ id: 29, cc: IEU },
		{ id: 30, cc: IEU },
		{ id: 31, cc: IEU },
		{ id: 32, cc: MIN },
		{ id: 33, cc: OFG },
		{ id: 34, cc: IEU },
		{ id: 35, cc: IEU },
		{ id: 36, cc: OPR },
		{ id: 37, cc: MIN },
		{ id: 38, cc: OFG },
		{ id: 39, cc: IEU },
		{ id: 40, cc: IEU },
		{ id: 41, cc: MIN },
		{ id: 42, cc: OFG },
	]
  },
  {
    id: 50,
    code: "IEU3205",
    course: "Taller de Planificación Urbana",
    semester: "X",
    year: 5,
    cc: IEU32,
    cr: 15,
    req: [
		{ id: 1, cc: CLG },
		{ id: 2, cc: SOL },
		{ id: 3, cc: MAT },
		{ id: 4, cc: PSI },
		{ id: 5, cc: IHI },
		{ id: 6, cc: VRA },
		{ id: 7, cc: VRA },
		{ id: 8, cc: VRA },
		{ id: 9, cc: ICP },
		{ id: 10, cc: ANT },
		{ id: 11, cc: GEO },
		{ id: 12, cc: EAE },
		{ id: 13, cc: OFG },
		{ id: 14, cc: CLG },
		{ id: 15, cc: OPR },
		{ id: 16, cc: OPR },
		{ id: 17, cc: OPR },
		{ id: 18, cc: OFG },
		{ id: 19, cc: OPR },
		{ id: 20, cc: OPR },
		{ id: 21, cc: OPR },
		{ id: 22, cc: MIN },
		{ id: 23, cc: OFG },
		{ id: 24, cc: IEU },
		{ id: 25, cc: IEU },
		{ id: 26, cc: OPR },
		{ id: 27, cc: MIN },
		{ id: 28, cc: OFG },
		{ id: 29, cc: IEU },
		{ id: 30, cc: IEU },
		{ id: 31, cc: IEU },
		{ id: 32, cc: MIN },
		{ id: 33, cc: OFG },
		{ id: 34, cc: IEU },
		{ id: 35, cc: IEU },
		{ id: 36, cc: OPR },
		{ id: 37, cc: MIN },
		{ id: 38, cc: OFG },
		{ id: 39, cc: IEU },
		{ id: 40, cc: IEU },
		{ id: 41, cc: MIN },
		{ id: 42, cc: OFG },
	]
  },
  {
    id: 51,
    code: "IEU3213",
    course: "Modelación Urbana",
    semester: "X",
    year: 5,
    cc: IEU32,
    cr: 5,
    req: [
		{ id: 1, cc: CLG },
		{ id: 2, cc: SOL },
		{ id: 3, cc: MAT },
		{ id: 4, cc: PSI },
		{ id: 5, cc: IHI },
		{ id: 6, cc: VRA },
		{ id: 7, cc: VRA },
		{ id: 8, cc: VRA },
		{ id: 9, cc: ICP },
		{ id: 10, cc: ANT },
		{ id: 11, cc: GEO },
		{ id: 12, cc: EAE },
		{ id: 13, cc: OFG },
		{ id: 14, cc: CLG },
		{ id: 15, cc: OPR },
		{ id: 16, cc: OPR },
		{ id: 17, cc: OPR },
		{ id: 18, cc: OFG },
		{ id: 19, cc: OPR },
		{ id: 20, cc: OPR },
		{ id: 21, cc: OPR },
		{ id: 22, cc: MIN },
		{ id: 23, cc: OFG },
		{ id: 24, cc: IEU },
		{ id: 25, cc: IEU },
		{ id: 26, cc: OPR },
		{ id: 27, cc: MIN },
		{ id: 28, cc: OFG },
		{ id: 29, cc: IEU },
		{ id: 30, cc: IEU },
		{ id: 31, cc: IEU },
		{ id: 32, cc: MIN },
		{ id: 33, cc: OFG },
		{ id: 34, cc: IEU },
		{ id: 35, cc: IEU },
		{ id: 36, cc: OPR },
		{ id: 37, cc: MIN },
		{ id: 38, cc: OFG },
		{ id: 39, cc: IEU },
		{ id: 40, cc: IEU },
		{ id: 41, cc: MIN },
		{ id: 42, cc: OFG },
	]
  },
  {
    id: 52,
    code: "IEU3210",
    course: "Gestión y Evaluación de Proyectos",
    semester: "X",
    year: 5,
    cc: IEU32,
    cr: 5,
    req: [
		{ id: 1, cc: CLG },
		{ id: 2, cc: SOL },
		{ id: 3, cc: MAT },
		{ id: 4, cc: PSI },
		{ id: 5, cc: IHI },
		{ id: 6, cc: VRA },
		{ id: 7, cc: VRA },
		{ id: 8, cc: VRA },
		{ id: 9, cc: ICP },
		{ id: 10, cc: ANT },
		{ id: 11, cc: GEO },
		{ id: 12, cc: EAE },
		{ id: 13, cc: OFG },
		{ id: 14, cc: CLG },
		{ id: 15, cc: OPR },
		{ id: 16, cc: OPR },
		{ id: 17, cc: OPR },
		{ id: 18, cc: OFG },
		{ id: 19, cc: OPR },
		{ id: 20, cc: OPR },
		{ id: 21, cc: OPR },
		{ id: 22, cc: MIN },
		{ id: 23, cc: OFG },
		{ id: 24, cc: IEU },
		{ id: 25, cc: IEU },
		{ id: 26, cc: OPR },
		{ id: 27, cc: MIN },
		{ id: 28, cc: OFG },
		{ id: 29, cc: IEU },
		{ id: 30, cc: IEU },
		{ id: 31, cc: IEU },
		{ id: 32, cc: MIN },
		{ id: 33, cc: OFG },
		{ id: 34, cc: IEU },
		{ id: 35, cc: IEU },
		{ id: 36, cc: OPR },
		{ id: 37, cc: MIN },
		{ id: 38, cc: OFG },
		{ id: 39, cc: IEU },
		{ id: 40, cc: IEU },
		{ id: 41, cc: MIN },
		{ id: 42, cc: OFG },
	]
  },
  {
    id: 53,
    code: "IEU32XX",
    course: "Optativo",
    semester: "X",
    year: 5,
    cc: OPR32,
    cr: 5,
    req: [
		{ id: 24, cc: IEU },
		{ id: 25, cc: IEU },
		{ id: 29, cc: IEU },
		{ id: 30, cc: IEU },
		{ id: 31, cc: IEU },
		{ id: 34, cc: IEU },
		{ id: 35, cc: IEU },
		{ id: 39, cc: IEU },
		{ id: 40, cc: IEU },
	]
  },
  {
    id: 54,
    code: "IEU32XX",
    course: "Optativo",
    semester: "X",
    year: 5,
    cc: OPR32,
    cr: 5,
    req: [
		{ id: 24, cc: IEU },
		{ id: 25, cc: IEU },
		{ id: 29, cc: IEU },
		{ id: 30, cc: IEU },
		{ id: 31, cc: IEU },
		{ id: 34, cc: IEU },
		{ id: 35, cc: IEU },
		{ id: 39, cc: IEU },
		{ id: 40, cc: IEU },
	]
  },
  {
    id: 55,
    code: "IEU3206",
    course: "Plan de Intervención Urbana",
    semester: "XI",
    year: 6,
    cc: IEU32,
    cr: 25,
    req: [
		{ id: 43, cc: IEU },
		{ id: 44, cc: IEU },
		{ id: 45, cc: IEU },
		{ id: 48, cc: IEU },
		{ id: 49, cc: IEU },
		{ id: 50, cc: IEU },
	]
  },
  {
    id: 56,
    code: "IEU3211",
    course: "Práctica Profesional",
    semester: "XI",
    year: 6,
    cc: IEU32,
    cr: 15,
    req: [
		{ id: 46, cc: IEU },
	]
  },
  {
    id: 57,
    code: "IEU32XX",
    course: "Optativo",
    semester: "XI",
    year: 6,
    cc: OPR32,
    cr: 5,
    req: [
		{ id: 24, cc: IEU },
		{ id: 25, cc: IEU },
		{ id: 29, cc: IEU },
		{ id: 30, cc: IEU },
		{ id: 31, cc: IEU },
		{ id: 34, cc: IEU },
		{ id: 35, cc: IEU },
		{ id: 39, cc: IEU },
		{ id: 40, cc: IEU },
	]
  },
  {
    id: 58,
    code: "IEU32XX",
    course: "Optativo",
    semester: "XI",
    year: 6,
    cc: OPR32,
    cr: 5,
    req: [
		{ id: 24, cc: IEU },
		{ id: 25, cc: IEU },
		{ id: 29, cc: IEU },
		{ id: 30, cc: IEU },
		{ id: 31, cc: IEU },
		{ id: 34, cc: IEU },
		{ id: 35, cc: IEU },
		{ id: 39, cc: IEU },
		{ id: 40, cc: IEU },
	]
  },
  {
    id: 59,
    code: "IEU32XX",
    course: "Optativo",
    semester: "XI",
    year: 6,
    cc: OPR32,
    cr: 5,
    req: [
		{ id: 24, cc: IEU },
		{ id: 25, cc: IEU },
		{ id: 29, cc: IEU },
		{ id: 30, cc: IEU },
		{ id: 31, cc: IEU },
		{ id: 34, cc: IEU },
		{ id: 35, cc: IEU },
		{ id: 39, cc: IEU },
		{ id: 40, cc: IEU },
	]
  },
  {
    id: 60,
    code: "IEU32XX",
    course: "Optativo",
    semester: "XI",
    year: 6,
    cc: OPR32,
    cr: 5,
    req: [
		{ id: 24, cc: IEU },
		{ id: 25, cc: IEU },
		{ id: 29, cc: IEU },
		{ id: 30, cc: IEU },
		{ id: 31, cc: IEU },
		{ id: 34, cc: IEU },
		{ id: 35, cc: IEU },
		{ id: 39, cc: IEU },
		{ id: 40, cc: IEU },
	]
  },
];